#.travis.yml

language: node_js

node_js:
  - "8.8.1"

cache:
  directories:
     - ./node_modules
branches:
  only:
    - master

before_install:
  # Install npm 5.
  - npm install -g npm@~5.5.1

install:
 - npm install -g firebase-tools
 - npm install

stages:
 - build
 - deploy_github
 - deploy_firebase

matrix:
  fast_finish: true
  include:
    # Build Stage
    - stage: build
      script: npm run build

    # Deploy on GitHub
    - stage: deploy_github
      script: echo “Deploying on github”
      after_success: |
        if [ -n "$GITHUB_API_KEY" ]; then
            cd "$TRAVIS_BUILD_DIR"
            cd dist
            git init
            git checkout -b master
            git add .
            git -c user.name='travis' -c user.email='travis' commit -m init
            # Make sure to make the output quiet, or else the API token will leak!
            # This works because the API key can replace your password.
            git push -f -q https://rahulbhooteshwar:$GITHUB_API_KEY@github.com/rahulbhooteshwar/rahulbhooteshwar.github.io.git master &2>/dev/null
            cd "$TRAVIS_BUILD_DIR"
        fi

    # Deploy on Firebase
    - stage: deploy_firebase
      script: echo “Deploying on Firebase"
      after_success: |
        if [ -n "$FIREBASE_TOKEN" ]; then
           firebase deploy --project my-profile-59b39 --token $FIREBASE_TOKEN
        fi

notifications:
  email:
    on_failure: always
    on_success: always
